[package]
name = "rlogs-protocol-journal"
version.workspace = true
edition.workspace = true
license.workspace = true
rust-version.workspace = true

[dependencies]
rlogs-capture = { path = "../../../../../engine/capture" }
rlogs-core = { path = "../../../../../engine/core" }
rlogs-game-bpsr = { path = "../.." }
serde_json.workspace = true
