[package]
name = "rlogs-plugin-combat-meter"
version.workspace = true
edition.workspace = true
license.workspace = true
rust-version.workspace = true

[dependencies]
rlogs-combat = { path = "../../../engine/combat" }
rlogs-events = { path = "../../../engine/events" }
rlogs-log-format = { path = "../../../engine/log-format" }
rlogs-plugin-api = { path = "../../../engine/plugin-api" }
rlogs-plugin-runtime = { path = "../../../engine/plugin-runtime" }
serde.workspace = true
serde_json.workspace = true

[dev-dependencies]
rlogs-log-format = { path = "../../../engine/log-format" }
