[package]
name = "rlogs-plugin-sdk"
version.workspace = true
edition.workspace = true
license.workspace = true
rust-version.workspace = true

[dependencies]
rlogs-events = { path = "../../engine/events" }
rlogs-log-format = { path = "../../engine/log-format" }
rlogs-plugin-api = { path = "../../engine/plugin-api" }
rlogs-plugin-runtime = { path = "../../engine/plugin-runtime" }
serde.workspace = true
thiserror.workspace = true

[dev-dependencies]
serde_json.workspace = true
